### ISSUE TITLE
cannot find symbol class MifareDESFireKey!

### ISSUE THREAD

**Issue by anicej** [skjolber/desfire-tools-for-android#1]
After building this project I faced with "cannot find symbol class MifareDESFireKey" error .. So I checked it and I saw this class doesn't exist! 
What's the problem?

**Comment by skjolber** [comment]
Unclear, since the file exists her:

https://github.com/skjolber/desfire-tools-for-android/blob/master/libfreefare/src/main/java/com/github/skjolber/desfire/libfreefare/MifareDESFireKey.java

**Comment by anicej** [comment]
Yes you are write my problem was in extracting the project. it has 2 files : MifareDESFireKey and MifareDesfireKey and extractor replaced one in another.
thank you.
