### ISSUE TITLE
Cannot resolve symbol 'MifareDESFireKey'

### ISSUE THREAD

**Issue by kodoku4csl** [skjolber/desfire-tools-for-android#2]
I cannot find class MifareDESFireKey either. Is it same with class 'MifareDesFireKey'?
![mifare](https://user-images.githubusercontent.com/54981588/64419698-acf02780-d0c7-11e9-9cec-3405f7073ebf.png)

**Comment by skjolber** [comment]
Yeah, seems there is an issue with case-insensitive filesystem.

**Comment by kodoku4csl** [comment]
> Yeah, seems there is an issue with case-insensitive filesystem.

Is there supposed to be MifareDESFireKey that have different reference with MifareDesFireKey?
Because i tried rename all MifareDESFireKey with MifareDesFireKey but looks like thats not the problem

**Comment by skjolber** [comment]
https://github.com/skjolber/desfire-tools-for-android/blob/master/libfreefare/src/main/java/com/github/skjolber/desfire/libfreefare/MifareDesfireKey.java

vs 

https://github.com/skjolber/desfire-tools-for-android/blob/master/libfreefare/src/main/java/com/github/skjolber/desfire/libfreefare/MifareDESFireKey.java

**Comment by kodoku4csl** [comment]
> https://github.com/skjolber/desfire-tools-for-android/blob/master/libfreefare/src/main/java/com/github/skjolber/desfire/libfreefare/MifareDesfireKey.java
> 
> vs
> 
> https://github.com/skjolber/desfire-tools-for-android/blob/master/libfreefare/src/main/java/com/github/skjolber/desfire/libfreefare/MifareDESFireKey.java

oh my miss sorry
its working now after i rename the MifareDESFireKey so it not conflicted with MifareDesFireKey
thanks alot......
