### ISSUE TITLE
Missing class MifareDESFireKey when clonig the repo

### ISSUE THREAD

**Issue by AnonymUser14** [skjolber/desfire-tools-for-android#6]
Hi, unfortunately I can't get the app to compile because the class "MirefareDESFireKey" seems to be missing when I clone the repo. However, here on GitHub I can indeed find the class, is this intentional?

Kind regards

**Comment by skjolber** [comment]
@AnonymUser14 did you manage to work around this problem?

**Comment by AnonymUser14** [comment]
> @AnonymUser14 did you manage to work around this problem?

Yes, I had no problem with it when I downloaded from the GitHub site instead of cloning it. Thanks anyway!
